# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_explizit', models.BooleanField()),
                ('staff_explizit', models.BooleanField()),
                ('setzt_ueberweisungsbetrag', models.BooleanField()),
                ('setzt_nachfrist1', models.BooleanField()),
                ('setzt_nachfrist2', models.BooleanField()),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versandanschrift', models.TextField()),
                ('freitext', models.TextField()),
                ('kontoinhaber_in', models.CharField(max_length=400)),
                ('iban', models.CharField(max_length=67)),
                ('bic', models.CharField(max_length=14)),
                ('nachfrist1', models.DateField(default=None, null=True)),
                ('nachfrist1_briefdatum', models.DateField(default=None, null=True)),
                ('nachfrist2', models.DateField(default=None, null=True)),
                ('nachfrist2_briefdatum', models.DateField(default=None, null=True)),
                ('ueberweisungsbetrag', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('antragszeitpunkt', models.DateTimeField(auto_now_add=True)),
                ('letzte_bearbeitung', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antragsgrund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('an_frist_gebunden', models.BooleanField()),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Begruendung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.CharField(max_length=1024)),
                ('briefdatum', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag')),
            ],
        ),
        migrations.CreateModel(
            name='Briefvorlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('betreff', models.CharField(max_length=200)),
                ('anrede', models.CharField(max_length=200)),
                ('brieftext', models.TextField()),
                ('hat_nachweise', models.BooleanField()),
                ('hat_begruendung', models.BooleanField()),
                ('hat_freitext', models.BooleanField()),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markierung', models.CharField(choices=[('tag-default', 'Grau'), ('tag-danger', 'Rot'), ('tag-warning', 'Gelb'), ('tag-success', 'Grün'), ('tag-info', 'Blau')], default='tag-default', max_length=11)),
                ('datei', models.CharField(max_length=1024)),
                ('aktiv', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_tex', models.TextField()),
                ('liste_tex', models.TextField()),
                ('aktion_als_ueberwiesen_markieren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktion_als_ueberwiesen_markieren', to='backend.Aktion')),
                ('aktion_antrag_stellen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktion_antrag_stellen', to='backend.Aktion')),
                ('aktion_hochladen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktion_hochladen', to='backend.Aktion')),
                ('aktion_zurueckziehen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktion_zurueckziehen', to='backend.Aktion')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ist_undo', models.BooleanField(default=False)),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag')),
            ],
        ),
        migrations.CreateModel(
            name='Nachweis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(blank=True)),
                ('hochzuladen', models.BooleanField(default=True)),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestertyp', models.CharField(choices=[('WISE', 'Wintersemester'), ('SOSE', 'Sommersemester')], max_length=4)),
                ('jahr', models.CharField(max_length=9)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('antragsfrist', models.DateField()),
                ('anzeigefrist', models.DateField()),
                ('erster_tag', models.DateField()),
                ('letzter_tag', models.DateField()),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('klassen', models.CharField(max_length=200)),
                ('sort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uebergang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Aktion')),
                ('status_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebergang_to__set', to='backend.Status')),
                ('status_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebergang_from__set', to='backend.Status')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='uebergang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Uebergang'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='status_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='nachweis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Nachweis'),
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status'),
        ),
        migrations.AddField(
            model_name='brief',
            name='vorlage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Briefvorlage'),
        ),
        migrations.AddField(
            model_name='antragsgrund',
            name='nachweise',
            field=models.ManyToManyField(to='backend.Nachweis'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='grund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antragsgrund'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Semester'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Person'),
        ),
        migrations.AddField(
            model_name='aktion',
            name='briefvorlage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Briefvorlage'),
        ),
        migrations.AlterUniqueTogether(
            name='uebergang',
            unique_together=set([('status_start', 'aktion')]),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('semestertyp', 'jahr')]),
        ),
        migrations.AlterUniqueTogether(
            name='antrag',
            unique_together=set([('semester', 'user')]),
        ),
    ]
