# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('aktion', models.CharField(max_length=200)),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versandanschrift', models.TextField()),
                ('letzte_bearbeitung', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antragsgrund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nachweis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrikelnummer', models.IntegerField()),
                ('anschrift', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('WISE', 'Wintersemester'), ('SOSE', 'Sommersemester')], max_length=2)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='antrag',
            name='grund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antragsgrund'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Semester'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Person'),
        ),
        migrations.AddField(
            model_name='aktion',
            name='antrag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag'),
        ),
    ]
