# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 18:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('backend', '0001_initial'), ('backend', '0002_auto_20160727_1654'), ('backend', '0003_auto_20160727_1655'), ('backend', '0004_antragsgrund_beschreibung'), ('backend', '0005_semester_frist'), ('backend', '0006_auto_20160727_1711'), ('backend', '0007_auto_20160729_1522'), ('backend', '0008_auto_20160729_1648'), ('backend', '0009_remove_person_matrikelnummer'), ('backend', '0010_person_adresse'), ('backend', '0011_globalsettings'), ('backend', '0012_antrag_antragszeitpunkt')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('aktion', models.CharField(max_length=200)),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Antrag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versandanschrift', models.TextField()),
                ('letzte_bearbeitung', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Antragsgrund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Nachweis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('geburtsort', models.CharField(default='Berlin', max_length=200)),
                ('adresse', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestertyp', models.CharField(choices=[('WISE', 'Wintersemester'), ('SOSE', 'Sommersemester')], max_length=4)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jahr', models.CharField(default=2016, max_length=9)),
                ('antragsfrist', models.DateField(default=datetime.datetime(2016, 7, 27, 17, 9, 52, 884687))),
            ],
        ),
        migrations.AddField(
            model_name='antrag',
            name='grund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antragsgrund'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Semester'),
        ),
        migrations.AddField(
            model_name='antrag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Person'),
        ),
        migrations.AddField(
            model_name='aktion',
            name='antrag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag'),
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datei', models.CharField(max_length=1024)),
                ('aktiv', models.BooleanField()),
                ('antrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag')),
                ('nachweis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Nachweis')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('klassen', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='antrag',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antrag',
            name='bic',
            field=models.CharField(default='BBBBCCLLbbb', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antrag',
            name='iban',
            field=models.CharField(default='DE19123412341234123412', max_length=67),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='antrag',
            name='kontoinhaber_in',
            field=models.CharField(default='Max Muster', max_length=400),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Status')),
            ],
        ),
        migrations.AddField(
            model_name='antrag',
            name='antragszeitpunkt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 29, 18, 20, 21, 783818)),
            preserve_default=False,
        ),
    ]
