# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_squashed_0012_antrag_antragszeitpunkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='antragsgrund',
            name='nachweise',
            field=models.ManyToManyField(to='backend.Nachweis'),
        ),
        migrations.AlterField(
            model_name='antragsgrund',
            name='beschreibung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='geburtsort',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='semester',
            name='antragsfrist',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='jahr',
            field=models.CharField(max_length=9),
        ),
    ]
