# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:29
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from datetime import date

def erstelle_semester(apps, schema_editor):
	
	Semester = apps.get_model("backend", "Semester")
	
	gruppe_ss16, created = Group.objects.get_or_create(name='2016SS')
	gruppe_ws16, created = Group.objects.get_or_create(name='2016WS')
	gruppe_ss17, created = Group.objects.get_or_create(name='2017SS')
	
	ss16 = Semester()
	ss16.semestertyp = "SOSE"
	ss16.jahr = "2016"
	ss16.betrag = 169.6
	ss16.antragsfrist =  date(2016, 5, 10)
	ss16.anzeigefrist = date(2016, 10, 1)
	ss16.erster_tag =  date(2016, 4, 1)
	ss16.letzter_tag = date(2016, 9, 30)
	ss16.gruppe_id = gruppe_ss16.id
	ss16.save()
	
	ws16 = Semester()
	ws16.semestertyp = "WISE"
	ws16.jahr = "2016/2017"
	ws16.betrag = 173.0
	ws16.antragsfrist =  date(2016, 11, 10)
	ws16.anzeigefrist = date(2017, 4, 1)
	ws16.erster_tag =  date(2016, 10, 1)
	ws16.letzter_tag = date(2017, 3, 31)
	ws16.gruppe_id = gruppe_ws16.id
	ws16.save()
	
	ss17 = Semester()
	ss17.semestertyp = "SOSE"
	ss17.jahr = "2017"
	ss17.betrag = 174.4
	ss17.antragsfrist =  date(2017, 5, 10)
	ss17.anzeigefrist = date(2017, 10, 1)
	ss17.erster_tag =  date(2017, 4, 1)
	ss17.letzter_tag = date(2017, 9, 30)
	ss17.gruppe_id = gruppe_ss17.id
	ss17.save()

class Migration(migrations.Migration):

	dependencies = [
		('backend', '0002_initial_data'),
	]

	operations = [
		migrations.RunPython(erstelle_semester),
	]
