# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160727_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semestertyp',
            field=models.CharField(choices=[('WISE', 'Wintersemester'), ('SOSE', 'Sommersemester')], max_length=4),
        ),
    ]
