# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='daten_sofort_loeschen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
