# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160729_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='nachweis',
            name='hochzuladen',
            field=models.BooleanField(default=True),
        ),
    ]
