# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160727_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='antragsgrund',
            name='beschreibung',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
