# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_nachweis_hochzuladen'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='aktion',
            old_name='aktion',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='aktion',
            name='akteur',
        ),
        migrations.RemoveField(
            model_name='aktion',
            name='antrag',
        ),
        migrations.RemoveField(
            model_name='aktion',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='aktion',
            name='status_end',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status_end', to='backend.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aktion',
            name='status_start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='status_start', to='backend.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dokument',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nachweis',
            name='beschreibung',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='history',
            name='aktion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Aktion'),
        ),
        migrations.AddField(
            model_name='history',
            name='antrag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag'),
        ),
    ]
