# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160730_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktion',
            name='staff_explizit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aktion',
            name='user_explizit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
