# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160730_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='antrag',
            name='ueberweisungsbetrag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
