# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_semester_frist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='frist',
            new_name='antragsfrist',
        ),
    ]
