# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_antrag_ueberweisungsbetrag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antrag',
            name='ueberweisungsbetrag',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
