# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20160730_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='betragsanpassung_erlaubt',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='hochladen_erlaubt',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
