# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20160730_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='aktion_ueberweisungsbetrag_aendern',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='backend.Aktion'),
            preserve_default=False,
        ),
    ]
