# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antrag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Antrag')),
                ('vorlage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.Briefvorlage')),
                ('datei', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
