# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20160730_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='briefvorlage',
            old_name='tex_source',
            new_name='brieftext',
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='anrede',
            field=models.CharField(default='Hallo VORNAME NACHNAME!', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='briefvorlage',
            name='betreff',
            field=models.CharField(default='Dein Antrag auf Semesterticketrückerstattung FALLNUMMER', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brief_tex',
            field=models.TextField(default='lalala'),
            preserve_default=False,
        ),
    ]
