# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20160730_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='brief',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 31, 2, 6, 59, 313194)),
            preserve_default=False,
        ),
    ]
