# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_brief_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antragsgrund',
            name='identifier',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='antrag',
            unique_together=set([('semester', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('semestertyp', 'jahr')]),
        ),
    ]
