# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20160731_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktion',
            name='is_file_upload',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
