# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20160731_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='aktion_antrag_stellen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aktion_antrag_stellen', to='backend.Aktion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='aktion_ueberweisungsbetrag_aendern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktion_ueberweisungsbetrag_aendern', to='backend.Aktion'),
        ),
    ]
