# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20160731_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='geburtsort',
        ),
    ]
