# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20160731_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='zurueckziehen_erlaubt',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
