# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_status_zurueckziehen_erlaubt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktion',
            name='briefvorlage',
            field=models.ManyToManyField(to='backend.Briefvorlage'),
        ),
    ]
