# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_aktion_briefvorlage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktion',
            name='briefvorlage',
        ),
        migrations.AddField(
            model_name='aktion',
            name='briefvorlage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Briefvorlage'),
        ),
    ]
