# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20160731_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='sort',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
